### PR TITLE
Tag Extraction

### PR DESCRIPTION
**Pull request by fosskers**
This PR adds and exposes functions for extracting all the heading tags that were parsed within the document.

### CODE REVIEW

**Comment by fosskers** [comment]
Definitely a bug in tag parsing:
```
org-mode      >                 [ Section
org-mode      >                     { sectionHeading = Plain "A" :|
org-mode      >                         [ Plain "Heading"
org-mode      >                         , Tags
org-mode      >                             ( "tag" :| [] )
org-mode      >                         , Plain "1:"
org-mode      >                         ]
org-mode      >                     , sectionTags = []
```

**Comment by srid** [comment]
The bug appears to be here:

https://github.com/fosskers/org-mode/blob/3c2d7b5cf2c9de271ac0cef3d016d1487e02e718/org-mode/lib/Data/Org.hs#L367-L370

It allows only `letterChar` (alphabetic chars), but the org-manual says that tags can contain "letters, numbers, ‘_’, and ‘@’". https://orgmode.org/manual/Tags.html

**Comment by fosskers** [comment]
Yes that is certainly the source of the problem. I'm taking today off but will fix it tomorrow.

**Comment by fosskers** [comment]
Turns out there was a representation problem. The `Tags` variant of the `Words` enum never should have existed, hence your original tag extraction code had to account for it as well, even though tags only appear in heading lines.

**Pull request merged**
