### PR TITLE
Fix hackage links in README

### PR DESCRIPTION
**Pull request by srid**

### CODE REVIEW

**Comment by fosskers** [comment]
Good find, thanks!

**Comment by srid** [comment]
Yea, thanks for putting this library up, I'm gonna try using it https://github.com/srid/ema/issues/1 !

**Comment by fosskers** [comment]
Oh nice, good luck!

**Comment by fosskers** [comment]
Make sure to take a look at http://hackage.haskell.org/package/org-mode-lucid and https://hackage.haskell.org/package/skylighting-lucid as well.

**Comment by srid** [comment]
I use `blaze-html`, and got a basic version using `org-mode` working here: https://github.com/srid/ema/pull/2

For highlighting I used to use skylighting - but nowadays I'd just use a client-side highlighter, like https://prismjs.com/ ... though looking at your site, I can see the value of highlighting during site generation, as you get to control the layout and styling.

Markdown is still my go-to markup, but I'm evaluating org-mode for writing mainly 'outline' like content (a la workflowy, dynalist), with support for metadata at the individual item level.

**Pull request merged**
